config/routes.rb
Rails.application.routes.draw do

  get '/dashboard', to: 'users#dashboard'
  get '/upvote' => "posts#upvote"
  get '/downvote' => "posts#downvote"
  get '/category/:name', to: 'posts#category_post', as: 'post_with_category'
  get '/user/login', to: 'users#login', as: 'login'
  post '/user/login', to: 'users#check_credentials', as: 'check_credentials'
  post '/logout', to: 'users#logout', as: 'logout'
  get '/logout', to: 'users#logout', as: 'logged_out'
  resources :posts
  resources :categories
  resources :comments

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :posts, :joint_table => :categories_posts
	validates :category_name, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_and_belongs_to_many :categories, :joint_table => :categories_posts
	has_many :comments
	self.inheritance_column = nil
	validates :title, presence: true
	validates :content, presence: true

	def slug
	    title.downcase.gsub(" ", "-")
	end

	def to_param
		"#{id}-#{slug}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def new
		@category = Category.new
		respond_to do |format|
			format.js
		end
	end

	def create
		@category = Category.new(:category_name => params[:categories][:category_name])
		# @categories = Category.all
		if @category.save
			flash[:success] = "Category has been added."
			redirect_to new_post_path
		else
			redirect_to posts_path
		end
	end

	def post_params
	   	params.require(:category).permit(:category_name)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def new
		@comment = Comment.new
	end

	def create
		@post = Post.find(params[:id])
		@save_the_comment = Comment.new(:comment => params[:comment], :post_id => @post.id )
		if @save_the_comment.save
			redirect_to "/posts/#{params[:id]}-#{@post.title.downcase.parameterize}"
		end
	end

	def comment_params
      	params.require(:comment).permit(:comment, :post_id)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@all_posts = Post.all
		@posts = @all_posts.sort_by(&:created_at).reverse
		@categories = Category.all
	end

	def new
		render :layout => false
		@categories = Category.all
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
		@recent_posts = Post.last(5)
		@categories = Category.all
		@user_id = @post.user_id
		@user = User.find_by_id(@user_id)
		@username = @user.username
	end

	def create
		all_params = params
		@user = User.find_by_username(session[:username])
		@post = Post.new(:title => all_params[:title], :content=> all_params[:content])
		@user.posts << @post
		all_params.each do |key, value|
			if key.start_with?("category")
				category = Category.find_by_category_name(value)
				@post.categories << category
				@user.posts << @post
				@post.save!
			end
		end
		if @post.save
			flash[:success] = "Post has been published."
			redirect_to and return '/posts'
		else
		 	render 'new'
		end
	end

	def edit
 		@post = Post.find(params[:id])
		render :layout => false
	end

	def update
		@post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            redirect_to posts_path, :notice=>"Your post is updated!"
	    else
            render "edit"
        end
    end

	def destroy
	    @post = Post.find(params[:id])
        if @post.present?
        	@post.delete
            redirect_to '/dashboard', :notice=> "Your post has been deleted!"
        end
	end

	def upvote
		Post.increment_counter(:score, params[:id])
		@post = Post.find(params[:id])
		respond_to do |format|
			format.js
		end
		#redirect_to "/posts/#{params[:id]}-#{@post.title.downcase.parameterize}"
	end

	def downvote
		@post = Post.find(params[:id])
		Post.decrement_counter(:score, params[:id])
		logger.info(@post.score)
		redirect_to "/posts/#{params[:id]}-#{@post.title.downcase.parameterize}"
	end

	def category_post
		@category = Category.find_by_category_name(params[:name])
		@posts_with_categories = @category.posts
	end

	def post_params
      	params.require(:post).permit(:title, :content, :photo)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :login, only: [:dashboard]

	def dashboard
		if session[:username].nil?
			redirect_to '/user/login'
		else
			user = User.find_by_username(session[:username])
			@posts = user.posts.sort_by(&:created_at).reverse
			render :layout => false
		end
	end

	def login

	end

	def check_credentials
		username = params[:username]
		password = params[:password]
		user = User.find_by_username(username)
		if not user.nil?
			secured_password = Digest::SHA2.hexdigest(user.salt + password)
			if user.password == secured_password
				session[:username] = username
				redirect_to '/dashboard'
			else
				redirect_to '/user/login'
			end
		else
			redirect_to '/user/login'
		end
	end

	def logout
		session[:username] = nil;
		redirect_to '/posts'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_new.html.erb
<%= form_for :categories, {url: {controller: 'categories', action: 'create'}, remote: true} do |f| %>
	<%= f.text_field :category_name, placeholder: "Add New category" %>
	<%= f.submit "Add", method: 'post' %>
<% end -%>

app/views/categories/new.js.erb
$("#new_category").html("<%= escape_javascript(render 'categories/new') %>")
$("#new_categ").attr(href, "#")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs -->
	<meta charset="utf-8">
	<title>Valayism</title>
	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- Main Style -->
	<link rel="stylesheet" href="../assets/style.css">
	<!-- Skins -->
	<link rel="stylesheet" href="../assets/skins.css">
	<!-- Responsive Style -->
	<link rel="stylesheet" href="../assets/responsive.css">
	<!-- Favicons -->
	<link rel="stylesheet" type="text/css" href="../assets/css/font-awesome.min.css">
	<!-- <link rel="stylesheet" type="text/css" href="../assets/base.css">
	<link rel="stylesheet" type="text/css" href="../assets/lists.css">
	<link rel="stylesheet" type="text/css" href="../assets/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="../assets/css/fontello.css">
	<link rel="stylesheet" type="text/css" href="../assets/prettyPhoto.css">
	<link rel="stylesheet" type="text/css" href="../assets/animate-custom.css"> -->

</head>
<body class="body-boxed-2">

<div class="loader"><i class="loader_html fa-spin"></i></div>

<div id="wrap" class="stripe grid_1200 boxed-2">
	<div class="wrap-search">
		<form method="post">
			<input type="search" name="s" value="Search here ..." onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;">
		</form>
	</div><!-- End wrap-search -->
	<header id="header">
		<div class="container clearfix">
			<div class="logo"><%= link_to "Valayism" ,posts_path%></div><!-- End logo -->
			<div class="header-follow">
				<% if session[:username].nil? %>
					<div class="header-follow-a">Follow Me</div>
				<% end %>
			</div><!-- End header-follow -->
			<div class="header-search">
				<div class="header-search-a"><i class="fa fa-search"></i></div>
			</div><!-- End header-search -->
			<nav class="navigation">
				<ul>
					<li class="current_page_item mega-menu"><%= link_to "Home", posts_path %>
					</li>
					<% if not session[:username].nil? %>
						<li><%= link_to "Dashboard", dashboard_path, :method=> "get"%></li>
						<li><%= link_to "Logout", logged_out_path, :method => "get" %></li>
					<% end %>
				</ul>
			</nav><!-- End navigation -->
			<nav class="navigation_mobile navigation_mobile_main">
				<div class="navigation_mobile_click">Go to...</div>
				<ul></ul>
			</nav><!-- End navigation_mobile -->
		</div><!-- End container -->
	</header><!-- End header -->
	
	<div class="clearfix"></div>
	<!-- Section starts-->

	<div class="sections"> 
		<%= yield %>
	</div>
	<!-- End sections -->
	
	<div class="clearfix"></div>
	
	<footer id="footer">
		<div class="container">
			<div class="copyrights">Copyright 2015 Valayism.com </div>
			<div class="social-ul">
				<ul>
					<li class="social-facebook"><a href="https://www.facebook.com/valayvaidya28"><i class="fa fa-facebook"></i></a></li>
					<li class="social-twitter"><a href="https://www.facebook.com/valayism"><i class="fa fa-twitter"></i></a></li>
				</ul>
			</div><!-- End social-ul -->
		</div><!-- End container -->
	</footer><!-- End footer -->
	
</div><!-- End wrap -->

<div class="go-up"><i class="fa fa-chevron-up"></i></div>

<%= javascript_include_tag "jquery.min.js"%>
<%= javascript_include_tag "html5.js"%>
<%= javascript_include_tag "jquery.nicescroll.min.js"%>
<%= javascript_include_tag "modernizr.js"%>
<%= javascript_include_tag "jquery.isotope.min.js"%>
<%= javascript_include_tag "tabs.js"%>
<%= javascript_include_tag "jquery.prettyPhoto.js"%>
<%= javascript_include_tag "jquery.bxslider.min.js"%>
<%= javascript_include_tag "jquery.tweet.js"%>
<%= javascript_include_tag "jflickrfeed.min.js"%>
<%= javascript_include_tag "jquery.jribbble-1.0.1.ugly.js"%>
<%= javascript_include_tag "custom.js"%>


<!-- End js -->

</body>
</html>

app/views/posts/_new_blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Valayism | New Blog</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="../assets/bootstrap1.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- fullCalendar 2.2.5-->
    <!-- Theme style -->
    <link rel="stylesheet" href="../assets/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="../assets/_all-skins.min.css">
    <!-- iCheck -->
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="../assets/bootstrap3-wysihtml5.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

      <header class="main-header">
        <!-- Logo -->
        <a href="/posts" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>V</b></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Valayism</b></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="/assets/mine.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
              <p>Valay Vaidya</p>
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">Go blogging!</li>
            <li class="treeview">
							<a href="/posts">
								<i class="fa fa-home"></i><span>Home</span>
							</a>
						</li>
            <li class="treeview">
              <a href="/dashboard">
                <i class="fa fa-dashboard"></i><span>Dashboard </span>
              </a>
            </li>
            <li class="treeview active">
              <a href="/posts/new">
                <i class="fa fa-envelope"></i> <span>New Blog</span>
              </a>
            </li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <!-- Main content -->
			<%= form_tag(posts_path) do%>
        <section class="content">
          <div class="row">
            <div class="col-md-3">
							<%= link_to "Back to Dashboard", dashboard_path, :class=>"btn btn-primary btn-block margin-bottom"%>
            </div><!-- /.col -->
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">New Blog!</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <div class="form-group">
                    <%= text_field_tag :title, nil ,:class => "form-control", :placeholder => "Title:" %>
                  </div>
                  <div class="form-group">
                    <%= text_area_tag 'content', nil , :id => "compose-textarea", :class => "form-control", :style=>"height: 300px" %>
                  </div>
                </div><!-- /.box-body -->
                <div class="box-footer">
                  <div class="pull-right">
                    <button class="btn btn-default"><i class="fa fa-pencil"></i> Save</button>
                    <%= button_tag "Publish", :class=>"btn btn-primary" %>
                  </div>
                  <button class="btn btn-default"><i class="fa fa-times"></i> Discard</button>
                </div><!-- /.box-footer -->
              </div><!-- /. box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
			<% end %>
			  </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Control Sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->

    <!-- jQuery 2.1.4 -->
    <script src="../assets/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="../assets/bootstrap1.min.js"></script>
    <!-- Slimscroll -->
    <script src="../assets/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="../assets/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../assets/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../assets/demo.js"></script>
    <!-- iCheck -->
    <script src="../assets/icheck.min.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="../assets/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Page Script -->
    <script>
      $(function () {
        //Add text editor
        $("#compose-textarea").wysihtml5();
      });
    </script>
  </body>




</html>

app/views/posts/_upvote.html.erb
<%= link_to "Downvote",  downvote_path(:id => @post.id) %> <%= @post.score%>

app/views/posts/category_post.html.erb
<%= link_to "Home", posts_path %>

<% @posts_with_categories.each do |post| %>
	<h3><%= link_to post.title, post %></h3>
	<%= post.content %><br>
	<hr />
<% end %>

app/views/posts/dashboard.html.erb
<% content_for :title do %>Dashboard<% end %>
<%= link_to "New blog", new_post_path %>
<%= link_to "Home", posts_path %>
<br>
<% @posts.each do |post| %>
	<%= link_to post.title, post %><br>
	<%= link_to "Edit", edit_post_path(post) %>
	<%= link_to "Delete", post, :confirm=>"Are you sure?", :method=>:delete %>
<hr>
<% end %>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Valayism | New Blog</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/assets/bootstrap1.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- fullCalendar 2.2.5-->
    <!-- Theme style -->
    <link rel="stylesheet" href="/assets/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/assets/_all-skins.min.css">
    <!-- iCheck -->
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="/assets/bootstrap3-wysihtml5.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

      <header class="main-header">
        <!-- Logo -->
        <a href="/posts" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>V</b></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Valayism</b></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="/assets/mine.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
              <p>Valay Vaidya</p>
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">Go blogging!</li>
            <li class="treeview">
							<a href="/posts">
								<i class="fa fa-home"></i><span>Home</span>
							</a>
						</li>
            <li class="treeview">
              <a href="/dashboard">
                <i class="fa fa-dashboard"></i><span>Dashboard</span>
              </a>
            </li>
            <li class="treeview">
              <a href="/posts/new">
                <i class="fa fa-envelope"></i> <span>New Blog</span>
              </a>
            </li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <!-- Main content -->
			<%= form_for @post do |f| %>
        <section class="content">
          <div class="row">
            <div class="col-md-3">
							<%= link_to "Back to Dashboard", dashboard_path, :class=>"btn btn-primary btn-block margin-bottom"%>
            </div><!-- /.col -->
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Edit Blog!</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <div class="form-group">
                    <%= f.text_field :title,:class => "form-control", :placeholder => "Title:" %>
                  </div>
                  <div class="form-group">
                    <%= f.text_area 'content' , :id => "compose-textarea", :class => "form-control", :style=>"height: 300px" %>
                  </div>
                </div><!-- /.box-body -->
                <div class="box-footer">
                  <div class="pull-right">
                    <button class="btn btn-default"><i class="fa fa-pencil"></i> Save</button>
                    <%= f.submit "Update", :class=>"btn btn-primary" %>
                  </div>
                  <button class="btn btn-default"><i class="fa fa-times"></i> Discard</button>
                </div><!-- /.box-footer -->
              </div><!-- /. box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
			<% end %>
			  </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Control Sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->
    <!-- jQuery 2.1.4 -->
    <script src="/assets/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="/assets/bootstrap1.min.js"></script>
    <!-- Slimscroll -->
    <script src="/assets/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/assets/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/assets/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/assets/demo.js"></script>
    <!-- iCheck -->
    <script src="/assets/icheck.min.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="/assets/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Page Script -->
    <script>
      $(function () {
        //Add text editor
        $("#compose-textarea").wysihtml5();
      });
    </script>
  </body>




</html>

app/views/posts/show.html.erb
<div class="sections">
			<div class="sections">
		<div class="container">
			<div class="row">
				<div class="col-md-8 main-content">
					<div class="post post-2 post-gallery single-post">
						<div class="post-head"><h3><%= @post.title %>.</h3>
							<div class="post-meta">
								<div><i class="fa fa-clock-o"></i><%= @post.created_at.to_time.strftime('%B %e')%></div>
								<div><i class="fa fa-heart"></i><a href="single-blog.html#"><%= @post.score %></a></div>
							</div><!-- End post-meta -->
							<div class="clearfix"></div>
						</div><!-- End post-head -->
						<div class="post-wrap">
							<div class="post-inner">
								<%= raw @post.content %>
								<div class="clearfix"></div>
										<div class="post-meta">
											<div class="post-meta-share">
												<i class="fa fa-share-alt"></i>
												<a href="#">Share This</a>
												<div class="share-social">
													<ul>
														<li class="social-facebook"><a href="http://www.facebook.com/sharer.php?u=<%=post_url(@post)%>"><i class="fa fa-facebook"></i></a></li>
														<li class="social-twitter"> <a href="http://twitter.com/home?status=<%=@post.title%> <%=post_url(@post)%> by @Valayism "><i class="fa fa-twitter"></i></a></li>
													</ul>
													<i class="fa fa-caret-down"></i>
												</div><!-- End follow-social -->

											</div>
											<div style="margin-left:2%"><i class="fa fa-thumbs-up" style="margin-left:10px"></i><a href=""></a></div>
										</div><!-- End post-meta -->
									<div class="clearfix"></div>
							</div>

						</div><!-- End post-wrap -->
					</div><!-- End post -->
					<div class="height_20"></div>

				</div><!-- End main-content -->
				<div class="col-md-4 sidebar">
					<div class="widget widget-about">
						<div class="widget-about-img"><img alt="" src="images/about-img.png"></div>
						<h3>Valay Vaidya</h3>
						<p>I have my own theory of everything.</p>
						<div class="clearfix"></div>
					</div><!-- End widget -->

					<div class="widget">
						<div class="widget-title"><i class="fa fa-folder-open"></i>Categories</div>
						<div class="widget-categories">
							<ul>
								<% @categories.each do |c| %>
									<li><%= link_to c.category_name, post_with_category_path(name: c.category_name) %></li>
								<% end %>
							</ul>
						</div><!-- End widget-categories -->
					</div><!-- End widget -->
					<div class="widget">
						<div class="widget-title"><i class="fa fa-bolt"></i>Recent Posts</div>
						<div class="widget-posts">
							<ul>
								<li class="widget-posts-image">
									<% @recent_posts.each do |post| %>
										<div class="widget-posts-content">
											<%= link_to post.title, post%>
											<span><i class="fa fa-clock-o"></i><%= post.created_at.to_time.strftime('%B %e') %></span>
										</div>
									<% end %>
								</li>
							</ul>
						</div><!-- End widget-posts -->
					</div><!-- End widget -->
					<div class="widget">
						<div class="widget-title"><i class="fa fa-twitter"></i>Latest Tweets<a class="twitter-follow" href="index-7.html#">Follow</a></div>
						<div class="widget-twitter"></div>
					</div><!-- End widget -->


				</div>
			</div><!-- End row -->
		</div><!-- End container -->
	</div>
</div>
<div id="upvote-button">
	<%= link_to "upvote",  upvote_path(:id => @post.id), remote: true, id: "upvote_post" %> <%= @post.score%>
</div>

app/views/users/login.html.erb
<%= form_tag (check_credentials_path) do %>
	<p>
		<%= label_tag :username%> <br />
		<%= text_field_tag :username %>
	</p>
	<p>
		<%= label_tag :password%> <br />
		<%= password_field_tag :password %>
	</p>
	<p>
		<%= button_tag "Login" %> 
	</p>
<% end %>